classdef Quantities

    properties (Constant)
        % https://en.wikipedia.org/wiki/List_of_physical_quantities
        Library = getQuantityLibrary()
        List = getQuantityLibrary().keys
    end

    methods (Static)
        function quantityName = getQuantityName(value)
            libValues = [engtools.unit.Quantities.Library.values.Value];
            matchingIndex = find(all(libValues == value));
            if ~isempty(matchingIndex)
                quantityName = engtools.unit.Quantities.List(matchingIndex(1));
            else
                quantityName = "Complex Quantity";
            end
        end
    end

end

function lib = getQuantityLibrary()

import engtools.unit.Quantity

lib = dictionary( ...
    "Dimensionless", Quantity(), ...
    "Time", Quantity(time = 1), ...
    "Length", Quantity(length = 1), ...
    "Mass", Quantity(mass = 1), ...
    "Temperature", Quantity(temperature = 1), ...
    "Current", Quantity(current = 1), ...
    "Amount Of Substance", Quantity(amountOfSubstance = 1), ...
    "Luminous Intensity", Quantity(luminousIntensity = 1), ...
    "Angle", Quantity(), ...
    "Absement", Quantity(time = 1, length = 1), ...
    "Absorbed Dose Rate", Quantity(time = -3, length = 2), ...
    "Acceleration", Quantity(time = -2, length = 1), ...
    "Action" ,Quantity(time = -1, length = 2, mass = 1), ...
    "Angular Acceleration", Quantity(time = -2), ...
    "Angular Momentum", Quantity(time = -1, length = 2, mass = 1), ...
    "Angular Velocity", Quantity(time = -1), ...
    "Area", Quantity(length = 2), ...
    "Area Density", Quantity(length = -2, mass = 1), ...
    "Capacitance", Quantity(time = 4, length = -2, mass = -1, current = 2), ...
    "Catalytic Activity Concentration", ...
        Quantity(time = -1, length = -3, amountOfSubstance = 1), ...
    "Centrifugal Force", Quantity(time = -2, length = 1, mass = 1), ...
    "Chemical Potential", ...
        Quantity(time = -2, length = 2, mass = 1, amountOfSubstance = 1), ...
    "Crackle", Quantity(time = -5, length = 1), ...
    "Current Density", Quantity(length = -2, current = 1), ...
    "Dose Equivalent", Quantity(time = -2, length = 2), ...
    "Dynamic Viscosity", Quantity(time = -1, length = -1, mass = 1), ...
    "Electric Charge", Quantity(time = 1, current = 1), ...
    "Electric Charge Density", Quantity(time = 1, length = -3, current = 1), ...
    "Electric Dipole Moment", Quantity(time = 1, length = 1, current = 1), ...
    "Electric Displacement Field", ...
        Quantity(time = 1, length = -2, current = 1), ...
    "Electric Field Strength", ...
        Quantity(time = -3, length = 1, mass = 1, current = -1), ...
    "Electrical Conductance", ...
        Quantity(time = 3, length = -2, mass = 1, current = 2), ...
    "Electrical Conductivity", ...
        Quantity(time = 3, length = -3, mass = -1, current = 2), ...
    "Electric Potential", ...
        Quantity(time = -3, length = 2, mass = 1, current = -1), ...
    "Electrical Resistance", ...
        Quantity(time = -3, length = 2, mass = 1, current = -2), ...
    "Electrical Resistivity", ...
        Quantity(time = -3, length = 3, mass = 1, current = -2), ...
    "Energy", Quantity(time = -2, length = 2, mass = 1), ...
    "Energy Density", Quantity(time = 2, length = -1, mass = 1), ...
    "Force", Quantity(time = -2, length = 1, mass = 1), ...
    "Frequency", Quantity(time = -1), ...
    "Half-Life", Quantity(time = 1), ...
    "Heat", Quantity(time = -2, length = 2, mass = 1), ...
    "Heat Capacity", ...
        Quantity(time = -2, length = 2, mass = 1, temperature = -1), ...
    "Heat Flux Density", Quantity(time = -3, mass = 1), ...
    "Illuminance", Quantity(length = -2, luminousIntensity = 1), ...
    "Impedance", Quantity(time = -3, length = 2, mass = 1, current = -2), ...
    "Impulse", Quantity(time = -1, length = 1, mass = 1), ...
    "Inductance", Quantity(time = -2, length = 2, mass = 1, current = -2), ...
    "Irradiance", Quantity(time = -3, mass = 1), ...
    "Intensity", Quantity(time = -3, mass = 1), ...
    "Jerk", Quantity(time = -3, length = 1), ...
    "Jounce", Quantity(time = -4, length = 1), ...
    "Linear Density", Quantity(length = -1, mass = 1), ...
    "Luminous Flux", Quantity(luminousIntensity = 1), ...
    "Mach Number", Quantity(), ...
    "Magnetic Field Strength", Quantity(length = -1, current = 1), ...
    "Magnetic Flux", ...
        Quantity(time = -2, length = 2, mass = 1, current = -1), ...
    "Magnetic Flux Density", Quantity(time = -2, mass = 1, current = -1), ...
    "Magnetic Moment", Quantity(length = 2, current = 1), ...
    "Magnetization", Quantity(length = -1, current = 1), ...
    "Mass Fraction", Quantity(), ...
    "Density", Quantity(length = -3, mass = 1), ...
    "Mean Lifetime", Quantity(time = 1), ...
    "Molar Concentration", Quantity(length = -3, amountOfSubstance = 1), ...
    "Molar Energy", ...
        Quantity(time = -2, length = 2, mass = 1, amountOfSubstance = -1), ...
    "Molar Entropy", Quantity(time = -2, length = 2, mass = 1, ...
        temperature = -1, amountOfSubstance = -1), ...
    "Molar Heat Capacity", Quantity(time = -2, length = 2, mass = 1, ...
        temperature = -1, amountOfSubstance = -1), ...
    "Moment Of Inertia", Quantity(length = 2, mass = 1), ...
    "Momentum", Quantity(time = -1, length = 1, mass = 1), ...
    "Optical Power", Quantity(length = -1), ...
    "Permeability", Quantity(time = -2, length = 1, mass = 1, current = -2), ...
    "Permittivity", Quantity(time = 4, length = -3, mass = -1, current = 2), ...
    "Plane Angle", Quantity(), ...
    "Pop", Quantity(time = -6, length = 1), ...
    "Power", Quantity(time = -3, length = 2, mass = 1), ...
    "Pressure", Quantity(time = -2, length = -1, mass = 1), ...
    "Pressure Gradient", Quantity(time  = -2, length = -2, mass = 1), ...
    "Activity", Quantity(time = -1), ...
    "Dose", Quantity(time = -2, length = 2), ...
    "Radiance", Quantity(time = -3, mass = 1), ...
    "Radiant Intensity", Quantity(time = -3, length = 2, mass = 1), ...
    "Reaction Rate", ...
        Quantity(time = -1, length = -3, amountOfSubstance = 1), ...
    "Refractive Index", Quantity(), ...
    "Reluctance", Quantity(time = 2, length = -2, mass = -1, current = 2), ...
    "Solid Angle", Quantity(), ...
    "Specific Energy", Quantity(time = -2, length = 2), ...
    "Specific Heat Capacity", ...
        Quantity(time = -2, length = 2, temperature = -1), ...
    "Specific Volume", Quantity(length = 3, mass = -1), ...
    "Spin", Quantity(time = -1, length = 2, mass = 1), ...
    "Strain", Quantity(), ...
    "Stress", Quantity(time = -2, length = -1, mass = 1), ...
    "Surface Tension", Quantity(time = -2, mass = 1), ...
    "Temperature Gradient", Quantity(length = -1, temperature = 1), ...
    "Thermal Conductance", ...
        Quantity(time = -3, length = 2, mass = 1, temperature = -1), ...
    "Thermal Conductivity", ...
        Quantity(time = -3, length = 1, mass = 1, temperature = -1), ...
    "Thermal Resistance",  ...
        Quantity(time = 3, length = -2, mass = -1, temperature = 1), ...
    "Thermal Resistivity", ...
        Quantity(time = 3, length = -1, mass = -1, temperature = 1), ...
    "Torque", ...
        Quantity(time = -2, length = 2, mass = 1), ...
    "Velocity", Quantity(time = -1, length = 1), ...
    "Volume", Quantity(length = 3), ...
    "Volumetric Flow Rate", Quantity(time = -1, length = 3), ...
    "Wavelength", Quantity(length = 1), ...
    "Wavenumber", Quantity(length = -1), ...
    "Wavevector", Quantity(length = -1), ...
    "Weight", Quantity(time = -2, length = 1, mass = 1), ...
    "Work", Quantity(time = -2, length = 2, mass = 1), ...
    "Young's Modulus", Quantity(time = -2, length = -1, mass = 1), ...
    "Spring Constant", Quantity(time = -2, mass = 1));

end